export const propertiesList = [
    {
        "createdBy": null,
        "createdDate": null,
        "updatedDate": null,
        "updatedBy": null,
        "active": null,
        "uid": 3,
        "propertyId": 11,
        "discountAmt": 700,
        "actualAmt": 1245.9,
        "propertyName": null,
        "title": "Villa in coral gables",
        "area": "3500Sq Ft",
        "status": "For sale",
        "bedrooms": "3",
        "bathrooms": "2",
        "garages": "2",
        "description": "",
        "size": "2BHK",
        "features": "SWIMMING POOL/ 3 STORIES/ CENTRAL COOLING/ JOG PATH 2/ 2 LAWN/BIKE PATH",
        "waterfront": "yes",
        "builtIn": "2003",
        "parking": "2 Or More Spaces,Covered Parking,Valet Parking",
        "view": "Intracoastal View,Direct ew",
        "waterfrontDescription": "Intracoastal Front,Ocean Access",
        "propertyAgentName": "",
        "agentAddress": "",
        "agentEmail": "",
        "agentMobile": "",
        "agentDescription": ""
    },
    {
        "createdBy": null,
        "createdDate": null,
        "updatedDate": null,
        "updatedBy": null,
        "active": null,
        "uid": 4,
        "propertyId": 12,
        "discountAmt": 700,
        "actualAmt": 1245.9,
        "propertyName": null,
        "title": "Villa in coral gables",
        "area": "3500Sq Ft",
        "status": "For sale",
        "bedrooms": "3",
        "bathrooms": "2",
        "garages": "2",
        "description": "",
        "size": "2BHK",
        "features": "SWIMMING POOL/ 3 STORIES/ CENTRAL COOLING/ JOG PATH 2/ 2 LAWN/BIKE PATH",
        "waterfront": "yes",
        "builtIn": "2003",
        "parking": "2 Or More Spaces,Covered Parking,Valet Parking",
        "view": "Intracoastal View,Direct ew",
        "waterfrontDescription": "Intracoastal Front,Ocean Access",
        "propertyAgentName": "",
        "agentAddress": "",
        "agentEmail": "",
        "agentMobile": "",
        "agentDescription": ""
    },
    {
        "createdBy": null,
        "createdDate": null,
        "updatedDate": null,
        "updatedBy": null,
        "active": null,
        "uid": 5,
        "propertyId": 13,
        "discountAmt": 700,
        "actualAmt": 1245.9,
        "propertyName": "Property Name",
        "title": "Villa in coral gables",
        "area": "3500Sq Ft",
        "status": "For sale",
        "bedrooms": "3",
        "bathrooms": "2",
        "garages": "2",
        "description": "Property description",
        "size": "2BHK",
        "features": "SWIMMING POOL/ 3 STORIES/ CENTRAL COOLING/ JOG PATH 2/ 2 LAWN/BIKE PATH",
        "waterfront": "yes",
        "builtIn": "2003",
        "parking": "2 Or More Spaces,Covered Parking,Valet Parking",
        "view": "Intracoastal View,Direct ew",
        "waterfrontDescription": "Intracoastal Front,Ocean Access",
        "propertyAgentName": "Agent Name",
        "agentAddress": "Agent Adress",
        "agentEmail": "Agent Email",
        "agentMobile": "9898989899",
        "agentDescription": "Agent Description"
    }
]

export const purchasedProperties = [
    {
        "purchaseId": 1,
        "transactionId": "FREE",
        "courseStatus": "Buy Completed",
        "propertyQuantity": 5,
        "courseName": null,
        "courseId": "13",
        "property": {
            "createdBy": null,
            "createdDate": null,
            "updatedDate": null,
            "updatedBy": null,
            "active": null,
            "uid": 5,
            "propertyId": 13,
            "discountAmt": 700,
            "actualAmt": 1245.9,
            "propertyName": "Property Name",
            "title": "Villa in coral gables",
            "area": "3500Sq Ft",
            "status": "For sale",
            "bedrooms": "3",
            "bathrooms": "2",
            "garages": "2",
            "description": "Property description",
            "size": "2BHK",
            "features": "SWIMMING POOL/ 3 STORIES/ CENTRAL COOLING/ JOG PATH 2/ 2 LAWN/BIKE PATH",
            "waterfront": "yes",
            "builtIn": "2003",
            "parking": "2 Or More Spaces,Covered Parking,Valet Parking",
            "view": "Intracoastal View,Direct ew",
            "waterfrontDescription": "Intracoastal Front,Ocean Access",
            "propertyAgentName": "Agent Name",
            "agentAddress": "Agent Adress",
            "agentEmail": "Agent Email",
            "agentMobile": "9898989899",
            "agentDescription": "Agent Description",
            "totalPropertyAvailable": 1000,
            "totalPropertySold": 0
        }
    }
]


